# Generated by Django 5.1.7 on 2025-06-08 04:45

import pronovetai_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pronovetai_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuildingGrade",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="grade_id", primary_key=True, serialize=False
                    ),
                ),
                ("description", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "pt_building_grades",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BuildingType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="type_id", primary_key=True, serialize=False
                    ),
                ),
                ("description", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "pt_building_types",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "image",
                    models.ImageField(
                        upload_to="images/",
                        validators=[pronovetai_app.models.validated_image_size],
                    ),
                ),
            ],
            options={
                "db_table": "pt_images",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("text", models.TextField(db_column="note_text")),
                ("created_at", models.DateTimeField(db_column="created_at")),
            ],
            options={
                "db_table": "pt_notes",
                "managed": False,
            },
        ),
        migrations.AlterModelTable(
            name="odform",
            table="pt_od_forms",
        ),
    ]
