# Generated by Django 5.1.7 on 2025-04-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pronovetai_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="building",
            old_name="for_sale",
            new_name="is_for_sale",
        ),
        migrations.RenameField(
            model_name="building",
            old_name="peza_certified",
            new_name="is_peza_certified",
        ),
        migrations.AddField(
            model_name="building",
            name="contact_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="building",
            name="contact_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("property_manager", "Property Manager"),
                    ("tenant", "Tenant"),
                    ("agent", "Agent"),
                    ("owner", "Owner"),
                    ("owner_representative", "Owner Representative"),
                    ("pta", "PTA"),
                    ("others", "Others"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
