# Generated by Django 5.1.7 on 2025-03-30 02:37

import django.db.models.deletion
import pronovetai_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pronovetai_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "street_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("barangay", models.CharField(blank=True, max_length=100, null=True)),
                ("city", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="company",
            name="barangay",
        ),
        migrations.RemoveField(
            model_name="company",
            name="city",
        ),
        migrations.RemoveField(
            model_name="company",
            name="street_address",
        ),
        migrations.AlterField(
            model_name="odform",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="company",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="companies",
                to="pronovetai_app.address",
            ),
        ),
        migrations.AlterField(
            model_name="building",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="buildings",
                to="pronovetai_app.address",
            ),
        ),
        migrations.CreateModel(
            name="BuildingImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="building_images/",
                        validators=[pronovetai_app.models.validated_image_size],
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="pronovetai_app.building",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UnitImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="unit_images/",
                        validators=[pronovetai_app.models.validated_image_size],
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="pronovetai_app.unit",
                    ),
                ),
            ],
        ),
    ]
