# Generated by Django 5.1.7 on 2025-06-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pronovetai_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="contact_type_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "description",
                    models.CharField(db_column="contact_type_desc", max_length=100),
                ),
            ],
            options={
                "db_table": "pt_contact_types",
                "managed": False,
            },
        ),
    ]
