# Generated by Django 5.1.7 on 2025-05-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pronovetai_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="user_type_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "description",
                    models.CharField(db_column="user_type_desc", max_length=255),
                ),
                ("created_at", models.DateTimeField(db_column="user_type_created")),
            ],
            options={
                "db_table": "pt_user_types",
                "managed": False,
            },
        ),
    ]
