# Generated by Django 5.1.7 on 2025-07-04 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pronovetai_app", "0002_contacttype"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="buildinggrade",
            options={"managed": False, "verbose_name": "building grade"},
        ),
    ]
