# Generated by Django 5.1.7 on 2025-04-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pronovetai_app", "0002_rename_for_sale_building_is_for_sale_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="building",
            name="contact_name",
        ),
        migrations.RemoveField(
            model_name="building",
            name="contact_type",
        ),
        migrations.AddField(
            model_name="building",
            name="contacts",
            field=models.ManyToManyField(
                blank=True, related_name="buildings", to="pronovetai_app.contact"
            ),
        ),
    ]
