# Generated by Django 5.1.7 on 2025-07-12 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pronovetai_app", "0003_alter_buildinggrade_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"managed": True},
        ),
    ]
