# Generated by Django 5.1.7 on 2025-04-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pronovetai_app", "0003_remove_building_contact_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="contact",
        ),
        migrations.AddField(
            model_name="contact",
            name="contact_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("property_manager", "Property Manager"),
                    ("tenant", "Tenant"),
                    ("agent", "Agent"),
                    ("owner", "Owner"),
                    ("owner_representative", "Owner Representative"),
                    ("pta", "PTA"),
                    ("others", "Others"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
