# Generated by Django 5.1.7 on 2025-07-12 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pronovetai_app", "0004_alter_company_options"),
    ]

    operations = []
