# Generated by Django 5.1.7 on 2025-07-15 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pronovetai_app", "0005_mark_pt_companies_seen"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"managed": False},
        ),
    ]
