# Generated by Django 5.1.7 on 2025-08-14 07:00

from django.db import migrations

CREATE_SQL = """
CREATE TABLE IF NOT EXISTS `pt_building_logs` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `building_id` BIGINT NOT NULL,
  `user_id` BIGINT NULL,
  `message` TEXT NOT NULL,
  `timestamp` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `pt_building_logs_building_fk` (`building_id`),
  KEY `pt_building_logs_user_fk` (`user_id`),
  CONSTRAINT `pt_building_logs_building_fk`
    FOREIGN KEY (`building_id`) REFERENCES `pt_buildings` (`building_id`) ON DELETE CASCADE,
  CONSTRAINT `pt_building_logs_user_fk`
    FOREIGN KEY (`user_id`) REFERENCES `pt_users` (`user_id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
"""

DROP_SQL = "DROP TABLE IF EXISTS `pt_building_logs`;"


class Migration(migrations.Migration):

    dependencies = [
        ("pronovetai_app", "0009_hash_plain_passwords"),
    ]

    operations = [
        migrations.RunSQL(sql=CREATE_SQL, reverse_sql=DROP_SQL),
    ]
